Kanan/AutoSetMTU.hpp, Kanan/BitmapFont.hpp, Kanan/DisableNagle.hpp, Kanan/Mod.hpp, Kanan/ShowCombatPower.hpp
Fixes inconsistent use of override and adds a virtual destructor to Mod.
=> Virtual inconsistency fixes

Kanan/FreeZoom.cpp, Kanan/FreeZoom.hpp, Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp
Ported over FreeZoom from old kanan
=> Added FreeZoom patch

Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp, Kanan/RangedAttackSwap.cpp, Kanan/RangedAttackSwap.hpp
switch by selecting the skill you want to swap
added as another ui option under borderless window
=> Added RangedAttackSwap

Kanan/Kanan.cpp, Kanan/Kanan.hpp, Kanan/KananInit.cpp, Loader/Main.cpp
- start a thread in dllmain to do the mod loading work since.
- added a modal as kanan loads
=> move loading to another thread

Kanan/FieldOfView.cpp, Kanan/FieldOfView.hpp
had some weird issues with field of view sometimes, so just a toggle to turn it off as well
=> Allow disable of Field of View

Kanan/EntityViewer.cpp, Kanan/FieldOfView.cpp, Kanan/Mabinogi.hpp
displays what the character is currently aggroing
useful for Song of Grief if you want to see who should desummon pet/crisis
=> FOV fix + current aggro target

Kanan/TTFFontSize.cpp, Kanan/TTFFontSize.hpp
I was able to replicate the issue seen in #24 and can confirm it is now functioning properly.
Also added original font size to the text input box, so it displays 11 now.
=> Fix TTFFontSize

Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp, Kanan/SecondaryPassword.cpp, Kanan/SecondaryPassword.hpp
Auto-inputs secondary password for you.
=> Add Secondary Password mod

Kanan/Kanan.cpp
Added option to force close the game (some information like the hotbar order won't be saved)
=> Option to close the game faster

Kanan/EquipmentOverride.cpp
Added option to auto apply equipment overrides on game start
=> Auto apply overrides on game start

Kanan/SecondaryPassword.cpp
Auto press Ok button on secondary password input keyboard
=> Auto login with secondary password

Kanan/Kanan.cpp
Now Force close option is 100% faster than before
=> Faster force close

Kanan/Patches.json
=> Fix IgnoreMaintainFrame

Kanan/Patches.json
https://github.com/cursey/kanan-new/issues/112
=> Add Unlimited Crafting Queue Patch

Kanan/EntityViewer.cpp, Kanan/EquipmentOverride.cpp
I don't have a face accessory to test that yet.
=> Fix Tail Override

Kanan/DontMoveToSquadChat.cpp, Kanan/DontMoveToSquadChat.hpp, Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp
=> Add Don't Move To Squad Chat

Kanan/KCamera.cpp, Kanan/KCamera.hpp, Kanan/Mabinogi.hpp
(I haven't used GitHub to do contributions much before so I hope this is working right)
Changed CCameraStates' viewMatrix to transformMatrix
Added KCamera with functions to get the view matrix and projection matrix, and get world-to-screen point
(I'm not 100% sure if the matrix transformations are working properly)
=> Updated Camera structures

Kanan/Patches.json
Update pattern for Force Client Side Devcat.
Add additional pattern to fix  Allow Hotkey For Any Item as it had broken following a patch late last year.
Resolves #172 , Resolves #169
=> Update Client Side Devcat and Allow Hotkeys For Any Item

Kanan/ChangeChannelHotkey.cpp, Kanan/ChangeChannelHotkey.hpp, Kanan/Game.cpp, Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp
uses the new onkeyup and onkeydown to allow for CC on hotkey
current hotkeys are L Shift + numpad0-9
added ChangeChannelHotkey.cpp
added ChangeChannelHotkey.hpp
edited game.cpp to allow channels 8~10 to work on nao (might cause issues on alexina not sure how to fix this)
added ChangeChannelHotkey to mods.cpp
~this time its a lot cleaner and might be worth merging :D?~
=> Change Channel on hotkey

Kanan/Patches.json
Update pattern for disable skill waitprocess locks and disable hotkey removal for vertical skill bars.
=> Update Disable Hotkey Removal and Disable Waitprocess Skill Locks

Kanan/EntityViewer.cpp, Kanan/EntityViewer.hpp
Counts Entities based on id. 
(made it cause I wanted to see how many players(alts) where afking in emain for the fishing event)
0x0010000000000001 - 0x0010000000FFFFFF for players
0x0010010000000001 - 0x0010010000FFFFFF for pets
0x0010f00000000001 -  0x0010f00000FFFFFF for npcs
=> Entity Counter

Kanan/Currtarget.cpp, Kanan/Currtarget.hpp, Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp
shows details about currently tarrgeted mob
info window only shows when local char has target or if the main kanan window is open
the codes super messy as a i made it in the middle of the night while high but it works
https://user-images.githubusercontent.com/20039012/147513618-958e53db-ac6c-40c5-bc44-de079a7211b7.mp4
=> Added target information

Kanan/CookingMod.cpp, Kanan/CookingMod.hpp, Kanan/Currtarget.cpp, Kanan/Kanan.vcxproj, Kanan/Kanan.vcxproj.filters, Kanan/Mods.cpp
https://user-images.githubusercontent.com/20039012/149606681-9bc25609-0b44-4d10-bc5e-e13012fbb5d2.mp4
=> Add Cooking mod

Kanan/CookingMod.cpp, Kanan/Patches.json
Fixed 
- cooking mod
- render wireframe
- show fps
added
- disable char rending
- disable prop rending
- show cloud and shadow information
=> Updates to some mods

Kanan/CookingMod.cpp, Kanan/Currtarget.cpp
=> Fixed Cooking Mod Scan

Launcher/LauncherApp.cpp
* this may have been a test server, this combo is no longer valid.
(#221)
=> Revert logip/port updates

Kanan/Kanan.cpp
Fix for https://github.com/cursey/kanan-new/issues/231
=> fixed metrics display not having a config

Kanan/Patches.json
Add the Bulk Buy x99 option to speedup patches in patches.json
=> Add Bulk Buy x99

Kanan/Patches.json
Add Ego Auto Select x30 to speedup patches and Enable prop target with skills loaded quality of life patches in patches.json
=> Add Ego Auto Select x30

Kanan/Mods.cpp, Kanan/RangedAttackSwap.cpp
Also clean up log entry to match the rest of the mods
=> Fix Range Attack Swap and re-enable curr target

.gitignore, Kanan/Patches.json
Ignore https://github.com/cursey/kanan-new/pull/282/commits/a03e6efe35d6f38c468e1444af19e725aeeebea1 & https://github.com/cursey/kanan-new/pull/282/commits/32945e6878a17b635b1bb82f8131730c9efd8205 Corrected formatting errors
- Inv while Dead
- Bitmap Font
- Elf Lag fix? (Hopefully works as expected)
- Add new Block AdSurvey on quit
=> Updated some of the byte patterns in Patches.json

Kanan/Patches.json
old scan returned too many results.
new scan finds 1 function and returns "correctly"
fix for https://github.com/cursey/kanan-new/issues/283
=> fix elf lag fix again

Kanan/Game.cpp
Update rendererAddress scan pattern for new client revision to fix crenderer based patches.
=> Update Game.cpp rendererAddress scan pattern

Kanan/Game.cpp, Kanan/Patches.json
Update hotkey any item pattern and patch.
=> Update hotkey any item

Kanan/Game.cpp, Kanan/Patches.json
Update patches.json to fix the pattern and patches for the reforge guide skip.
=> Update reforge guide skip

Kanan/ColorAltText.cpp, Kanan/CookingMod.cpp, Kanan/Patches.json
Update the patch and pattern for allow interface while dead. 
Update pattern for color alt text. Fixes #302 
Update don't close title window
=> Update more mods broken on 8/10/23

Kanan/Patches.json, Kanan/broken.json
reformat all patches to have the same code style
For issue 
https://github.com/cursey/kanan-new/issues/323
list of broken patches
```
[Logout In Conversation] Failed to find pattern E8 ? ? ? ? 84 C0 74 ? 41 8D ? ? E9
[Disable Censorship] Failed to find pattern 0F 84 ? ? ? ? 84 D2 0F 84 ? ? ? ? 85 FF
[Disable Skill Rankup Window] Failed to find pattern 75 ? 32 C0 8B 4D F4 64 89 0D ? ? ? ? 59 5F 5E 5B 8B E5 5D C2 ? ? 8B 46 0C
[Disable Skill Rankup Window] Failed to find pattern 0F 84 ? ? ? ? 8B 01 8B 35 ? ? ? ? FF 50 58 8B C8 E8 ? ? ? ? 50
[Disable Screen Shake] Failed to find pattern 8B 01 5E 89 42 48
[Disable Screen Shake] Failed to find pattern 8B 01 5E 89 42 48
[Disable Screen Shake] Failed to find pattern 8B 01 5E 89 42 48
[Disable Screen Shake] Failed to find pattern 8B 01 5E 89 42 48 …
```
=> Move Broken Patches to broken.json

Kanan/Patches.json, Kanan/broken.json
Update patches for Uncap Production, Disable Chat Filter, Mounted Prop Attack. Remove patches that are currently working from broken.json.
Fixes #322
=> Update Uncap Production, Disable Chat Filter, Mounted Prop Attack
